parameters:
- name: pythonVersion
  default: 3.10.0
- name: allowUnstable
  default: false
- name: arch
  default: 'x64'

jobs:
# MS-hosted
# - job:
#   displayName: ubuntu-20.04
#   pool:
#     vmImage: ubuntu-20.04
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: ubuntu-18.04
#   pool:
#     vmImage: ubuntu-18.04
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: macOS-11
#   pool:
#     vmImage: macOS-11
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: macOS-10.15
#   pool:
#     vmImage: macOS-10.15
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: windows-2019
#   pool:
#     vmImage: windows-2019
#   steps:
#   - template: ./win.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: windows-2022
#   pool:
#     vmImage: windows-2022
#   steps:
#   - template: ./win.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}

# Self-hosted
- job:
  displayName: self-hosted ubuntu
  pool:
    name: pool
  steps:
  - template: ./unix.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      allowUnstable: ${{ parameters.allowUnstable }}
      arch: ${{ parameters.arch }}
# - job:
#   displayName: self-hosted Windows
#   pool:
#     name: pool
#     demands:
#     - Agent.Name -equals win-default
#   steps:
#   - template: ./win.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: self-hosted Debian
#   pool:
#     name: pool
#     demands:
#     - Agent.Name -equals deb-default
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: self-hosted fedora
#   pool:
#     name: pool
#     demands:
#     - Agent.Name -equals fed-default
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: self-hosted opensuse
#   pool:
#     name: pool
#     demands:
#     - Agent.Name -equals sus-default
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
# - job:
#   displayName: self-hosted macos
#   pool:
#     name: pool
#     demands:
#     - Agent.Name -equals macos-as-runner
#   steps:
#   - template: ./unix.yml
#     parameters:
#       pythonVersion: ${{ parameters.pythonVersion }}
#       allowUnstable: ${{ parameters.allowUnstable }}
#       arch: ${{ parameters.arch }}
