parameters:
- name: pythonVersion
  default: 3.10.0

jobs:
- job:
  displayName: Unix
  strategy:
    matrix:
      ubuntu2004:
        imageName: ubuntu-20.04
      ubuntu1804:
        imageName: ubuntu-18.04
      macos11:
        imageName: macOS-11
      macos10:
        imageName: macOS-10.15
  steps:
  - task: UsePythonVersionM@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      addToPath: true
      architecture: 'x64'
  - script: 'if [[ $(python --version) != "Python ${{ parameters.pythonVersion }}" ]]; then exit 1; fi'

- job:
  displayName: Windows
  dependsOn: []
  strategy:
    matrix:
      windows2022:
        imageName: windows-2022
      windows2019:
        imageName: windows-2019
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersionM@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      addToPath: true
      architecture: 'x64'
  - powershell: 'if ( $(python --version) -ne "Python ${{ parameters.pythonVersion }}" ) { exit 1 }'
