parameters:
- name: pythonVersion
  default: 3.10.0

jobs:
- job:
  displayName: ubuntu-20.04
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: ./unix.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
- job:
  displayName: ubuntu-18.04
  pool:
    vmImage: ubuntu-18.04
  steps:
  - template: ./unix.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
- job:
  displayName: macOS-11
  pool:
    vmImage: macOS-11
  steps:
  - template: ./unix.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
- job:
  displayName: macOS-10.15
  pool:
    vmImage: macOS-10.15
  steps:
  - template: ./unix.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
- job:
  displayName: windows-2019
  pool:
    vmImage: windows-2019
  steps:
  - template: ./win.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
- job:
  displayName: windows-2022
  pool:
    vmImage: windows-2022
  steps:
  - template: ./win.yml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
